if (!requireNamespace("httr", quietly = TRUE)) install.packages("httr")
library(httr)
if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
library(dplyr)
if (!requireNamespace("stringr", quietly = TRUE)) install.packages("stringr")
library(stringr)
if (!requireNamespace("xml2", quietly = TRUE)) install.packages("xml2")
library(xml2)
if (!requireNamespace("writexl", quietly = TRUE)) install.packages("writexl")
library(writexl)